/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRootRouteImport } from './routes/_app-root'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as AppRootExploreRouteImport } from './routes/_app-root.explore'

const AppRootRoute = AppRootRouteImport.update({
  id: '/_app-root',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRootExploreRoute = AppRootExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRootRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRootRouteWithChildren
  '/explore': typeof AppRootExploreRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRootRouteWithChildren
  '/explore': typeof AppRootExploreRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app-root': typeof AppRootRouteWithChildren
  '/_app-root/explore': typeof AppRootExploreRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explore' | '/auth/signin' | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore' | '/auth/signin' | '/auth/signup'
  id:
    | '__root__'
    | '/_app-root'
    | '/_app-root/explore'
    | '/auth/signin'
    | '/auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRootRoute: typeof AppRootRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app-root': {
      id: '/_app-root'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-root/explore': {
      id: '/_app-root/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppRootExploreRouteImport
      parentRoute: typeof AppRootRoute
    }
  }
}

interface AppRootRouteChildren {
  AppRootExploreRoute: typeof AppRootExploreRoute
}

const AppRootRouteChildren: AppRootRouteChildren = {
  AppRootExploreRoute: AppRootExploreRoute,
}

const AppRootRouteWithChildren =
  AppRootRoute._addFileChildren(AppRootRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRootRoute: AppRootRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
