/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRootRouteImport } from './routes/_app-root'
import { Route as AppRootMyJobsRouteImport } from './routes/_app-root.my-jobs'
import { Route as AppRootExploreRouteImport } from './routes/_app-root.explore'
import { Route as AppRootAuthSignupRouteImport } from './routes/_app-root.auth.signup'
import { Route as AppRootAuthSigninRouteImport } from './routes/_app-root.auth.signin'

const AppRootRoute = AppRootRouteImport.update({
  id: '/_app-root',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRootMyJobsRoute = AppRootMyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootExploreRoute = AppRootExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootAuthSignupRoute = AppRootAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootAuthSigninRoute = AppRootAuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => AppRootRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRootRouteWithChildren
  '/explore': typeof AppRootExploreRoute
  '/my-jobs': typeof AppRootMyJobsRoute
  '/auth/signin': typeof AppRootAuthSigninRoute
  '/auth/signup': typeof AppRootAuthSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRootRouteWithChildren
  '/explore': typeof AppRootExploreRoute
  '/my-jobs': typeof AppRootMyJobsRoute
  '/auth/signin': typeof AppRootAuthSigninRoute
  '/auth/signup': typeof AppRootAuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app-root': typeof AppRootRouteWithChildren
  '/_app-root/explore': typeof AppRootExploreRoute
  '/_app-root/my-jobs': typeof AppRootMyJobsRoute
  '/_app-root/auth/signin': typeof AppRootAuthSigninRoute
  '/_app-root/auth/signup': typeof AppRootAuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explore' | '/my-jobs' | '/auth/signin' | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore' | '/my-jobs' | '/auth/signin' | '/auth/signup'
  id:
    | '__root__'
    | '/_app-root'
    | '/_app-root/explore'
    | '/_app-root/my-jobs'
    | '/_app-root/auth/signin'
    | '/_app-root/auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRootRoute: typeof AppRootRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app-root': {
      id: '/_app-root'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app-root/my-jobs': {
      id: '/_app-root/my-jobs'
      path: '/my-jobs'
      fullPath: '/my-jobs'
      preLoaderRoute: typeof AppRootMyJobsRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_app-root/explore': {
      id: '/_app-root/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppRootExploreRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_app-root/auth/signup': {
      id: '/_app-root/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AppRootAuthSignupRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_app-root/auth/signin': {
      id: '/_app-root/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AppRootAuthSigninRouteImport
      parentRoute: typeof AppRootRoute
    }
  }
}

interface AppRootRouteChildren {
  AppRootExploreRoute: typeof AppRootExploreRoute
  AppRootMyJobsRoute: typeof AppRootMyJobsRoute
  AppRootAuthSigninRoute: typeof AppRootAuthSigninRoute
  AppRootAuthSignupRoute: typeof AppRootAuthSignupRoute
}

const AppRootRouteChildren: AppRootRouteChildren = {
  AppRootExploreRoute: AppRootExploreRoute,
  AppRootMyJobsRoute: AppRootMyJobsRoute,
  AppRootAuthSigninRoute: AppRootAuthSigninRoute,
  AppRootAuthSignupRoute: AppRootAuthSignupRoute,
}

const AppRootRouteWithChildren =
  AppRootRoute._addFileChildren(AppRootRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRootRoute: AppRootRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
