services:
  db:
    image: docker.io/library/postgres:18-alpine
    container_name: studio_db_central
    env_file:
      - ../../.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # APP DATABSE CREDENTIALS
      - JC_DB_USER=${JC_DB_USER}
      - JC_DB_PASSWORD=${JC_DB_PASSWORD}
      - JC_DB_NAME=${JC_DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data:Z
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:Z

